name: Deploy Backend (Node.js)

on:
  push:
    branches: [ main ]
    paths: ['api/**']

env:
  AZURE_FUNCTIONAPP_NAME: 'deploy-automatico-pq-d3hxfvdbeea5b0b9'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api' 
  NODE_VERSION: '22.x'
  SCM_DO_BUILD_DURING_DEPLOYMENT: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies'
      shell: bash
      run: |
        pushd '.api/'
        npm install
        npm run build --if-present
        npm prune --production # Remove bibliotecas de teste para ficar leve
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '.api/'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}